# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZguHsvsHXJIPyPs9yCM-yFCYqU5Crd3W
"""

import streamlit as st

# Membuat judul
st.title("Reservasi Hotel")

# Membuat form input
nama = st.text_input("Nama Lengkap")
email = st.text_input("Email")

check_in = st.date_input("Tanggal Check-In")
check_out = st.date_input("Tanggal Check-Out")

# Membuat pilihan kamar
kamar = st.selectbox(
    "Pilih Tipe Kamar",
    ("Standard", "Superior", "Deluxe")
)

# Membuat checkbox untuk layanan tambahan
layanan = st.checkbox("Layanan Tambahan")

# Membuat tombol untuk submit
submit = st.button("Reservasi")

# Menampilkan hasil reservasi jika tombol submit ditekan
if submit:
    st.write("Terima kasih sudah melakukan reservasi dengan detail sebagai berikut:")
    st.write(f"Nama: {nama}")
    st.write(f"Email: {email}")
    st.write(f"Tanggal Check-In: {check_in}")
    st.write(f"Tanggal Check-Out: {check_out}")
    st.write(f"Tipe Kamar: {kamar}")
    if layanan:
        st.write("Layanan Tambahan: Ya")
    else:
        st.write("Layanan Tambahan: Tidak")